//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_text_set_H
#define METASPRITE_text_set_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define text_set_TILE_ORIGIN 0
#define text_set_TILE_W 8
#define text_set_TILE_H 8
#define text_set_WIDTH 64
#define text_set_HEIGHT 48
#define text_set_TILE_COUNT 48
#define text_set_MAP_ATTRIBUTES 0

BANKREF_EXTERN(text_set)

extern const uint8_t text_set_tiles[768];

extern const unsigned char text_set_map[48];
#define text_set_map_attributes text_set_map

#endif
